Mybranch
srlhyo/poetik pull request #1
Opened 2021-02-25 16:12 UTC by LailaL88

Added the styles to top part of site and created a modal

2021-02-25 16:20 UTC, srlhyo commented on wp-content/themes/poetiktheme/src/app.scss
> +// }
Why did you comment out?

2021-02-25 16:21 UTC, srlhyo requested changes
please review my comments

2021-02-25 16:26 UTC, LailaL88 commented on wp-content/themes/poetiktheme/src/app.scss
> +// }
yes

2021-02-26 15:38 UTC, closed without merging

2021-02-26 15:39 UTC, srlhyo commented
closed